// Export utilities for CSV and PDF generation

export interface ExportColumn {
  key: string;
  header: string;
  formatter?: (value: any) => string;
}

/**
 * Export data to CSV and trigger download
 */
export function exportToCSV<T extends Record<string, any>>(
  data: T[],
  columns: ExportColumn[],
  filename: string
): void {
  if (!data || data.length === 0) {
    console.warn('No data to export');
    return;
  }

  // Create header row
  const headers = columns.map(col => `"${col.header}"`).join(',');

  // Create data rows
  const rows = data.map(item => {
    return columns.map(col => {
      const value = item[col.key];
      const formatted = col.formatter ? col.formatter(value) : String(value ?? '');
      // Escape quotes and wrap in quotes
      return `"${formatted.replace(/"/g, '""')}"`;
    }).join(',');
  });

  const csv = [headers, ...rows].join('\n');
  
  // Add BOM for Excel compatibility
  const BOM = '\uFEFF';
  const blob = new Blob([BOM + csv], { type: 'text/csv;charset=utf-8;' });
  
  downloadBlob(blob, `${filename}.csv`);
}

/**
 * Export data to PDF using print dialog
 */
export function exportToPDF<T extends Record<string, any>>(
  data: T[],
  columns: ExportColumn[],
  title: string,
  filename: string
): void {
  if (!data || data.length === 0) {
    console.warn('No data to export');
    return;
  }

  const printContent = generatePrintHTML(data, columns, title);
  
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    console.error('Failed to open print window');
    return;
  }

  printWindow.document.write(printContent);
  printWindow.document.close();
  
  // Wait for styles to load then print
  printWindow.onload = () => {
    printWindow.focus();
    printWindow.print();
  };
}

/**
 * Generate print-friendly HTML
 */
function generatePrintHTML<T extends Record<string, any>>(
  data: T[],
  columns: ExportColumn[],
  title: string
): string {
  const tableRows = data.map(item => {
    const cells = columns.map(col => {
      const value = item[col.key];
      const formatted = col.formatter ? col.formatter(value) : String(value ?? '');
      return `<td>${escapeHtml(formatted)}</td>`;
    }).join('');
    return `<tr>${cells}</tr>`;
  }).join('');

  const tableHeaders = columns.map(col => `<th>${escapeHtml(col.header)}</th>`).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${escapeHtml(title)}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 20px;
          color: #1a1a1a;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 2px solid #e5e7eb;
        }
        h1 { font-size: 24px; margin-bottom: 8px; }
        .meta { color: #6b7280; font-size: 14px; }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 20px;
        }
        th, td {
          padding: 12px 8px;
          text-align: left;
          border-bottom: 1px solid #e5e7eb;
        }
        th {
          background: #f9fafb;
          font-weight: 600;
          font-size: 12px;
          text-transform: uppercase;
          color: #374151;
        }
        td { font-size: 14px; }
        tr:nth-child(even) { background: #f9fafb; }
        .footer {
          margin-top: 30px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          text-align: center;
          color: #9ca3af;
          font-size: 12px;
        }
        @media print {
          body { padding: 0; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${escapeHtml(title)}</h1>
        <p class="meta">Generated on ${new Date().toLocaleString()} | ${data.length} records</p>
      </div>
      <table>
        <thead><tr>${tableHeaders}</tr></thead>
        <tbody>${tableRows}</tbody>
      </table>
      <div class="footer">
        <p>This report was automatically generated by SMM Panel</p>
      </div>
    </body>
    </html>
  `;
}

/**
 * Download blob as file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Escape HTML entities
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Format currency
 */
export function formatCurrency(value: number | string): string {
  const num = typeof value === 'string' ? parseFloat(value) : value;
  return `$${num.toFixed(2)}`;
}

/**
 * Format date
 */
export function formatDate(value: string | Date): string {
  const date = typeof value === 'string' ? new Date(value) : value;
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

/**
 * Format percentage
 */
export function formatPercentage(value: number | string): string {
  const num = typeof value === 'string' ? parseFloat(value) : value;
  return `${num.toFixed(1)}%`;
}

// Pre-defined column sets for common exports
export const serviceColumns: ExportColumn[] = [
  { key: 'id', header: 'ID' },
  { key: 'name', header: 'Name' },
  { key: 'category', header: 'Category' },
  { key: 'price', header: 'Price', formatter: formatCurrency },
  { key: 'minQty', header: 'Min Qty' },
  { key: 'maxQty', header: 'Max Qty' },
  { key: 'status', header: 'Status' },
];

export const customerColumns: ExportColumn[] = [
  { key: 'name', header: 'Name' },
  { key: 'email', header: 'Email' },
  { key: 'status', header: 'Status' },
  { key: 'segment', header: 'Segment' },
  { key: 'balance', header: 'Balance', formatter: formatCurrency },
  { key: 'totalSpent', header: 'Total Spent', formatter: formatCurrency },
  { key: 'totalOrders', header: 'Orders' },
  { key: 'joinedAt', header: 'Joined', formatter: formatDate },
];

export const analyticsColumns: ExportColumn[] = [
  { key: 'date', header: 'Date', formatter: formatDate },
  { key: 'revenue', header: 'Revenue', formatter: formatCurrency },
  { key: 'orders', header: 'Orders' },
  { key: 'newUsers', header: 'New Users' },
  { key: 'conversionRate', header: 'Conversion', formatter: formatPercentage },
];

export const transactionColumns: ExportColumn[] = [
  { key: 'id', header: 'Transaction ID' },
  { key: 'date', header: 'Date', formatter: formatDate },
  { key: 'type', header: 'Type' },
  { key: 'method', header: 'Payment Method' },
  { key: 'amount', header: 'Amount', formatter: formatCurrency },
  { key: 'status', header: 'Status' },
  { key: 'customer', header: 'Customer' },
];
