import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { platformTranslations, sectionTranslations } from '@/lib/platform-translations';

export type Language = 'en' | 'es' | 'pt' | 'ar' | 'tr' | 'ru' | 'fr' | 'de' | 'zh' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  isRTL: boolean;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Merge platform translations with existing translations
const mergeTranslations = (base: Record<string, string>, platform: Record<string, string> | undefined) => {
  return { ...base, ...(platform || {}) };
};

// Comprehensive translation dictionaries
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Layout
    'nav.dashboard': 'Dashboard',
    'nav.services': 'Services',
    'nav.orders': 'My Orders',
    'nav.new_order': 'New Order',
    'nav.deposit': 'Add Funds',
    'nav.support': 'Support',
    'nav.profile': 'Profile',
    'nav.favorites': 'Favorites',
    'nav.track_order': 'Track Order',
    'nav.logout': 'Logout',
    'nav.menu': 'Menu',
    'nav.more': 'More',
    'nav.blog': 'Blog',
    'nav.api': 'API',
    'nav.bulk_order': 'Bulk Order',
    'nav.smm_services': 'SMM Services',
    'nav.your_balance': 'Your Balance',
    'nav.language': 'Language',
    'nav.currency': 'Currency',
    'nav.take_tour': 'Take a Tour',
    'nav.terms': 'Terms of Service',
    'nav.privacy': 'Privacy Policy',
    
    // Legal pages
    'legal.table_of_contents': 'Table of Contents',
    'legal.last_updated': 'Last updated',
    'legal.privacy_subtitle': 'How we collect, use, and protect your data',
    'legal.terms_subtitle': 'Please read these terms carefully before using our services',
    'common.print': 'Print',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.refresh': 'Refresh',
    'common.all': 'All',
    'common.view_all': 'View All',
    'common.retry': 'Retry',
    'common.close': 'Close',
    'common.copy': 'Copy',
    'common.copied': 'Copied!',
    'common.send': 'Send',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.details': 'Details',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': "Here's your account overview",
    'dashboard.balance': 'Balance',
    'dashboard.total_orders': 'Total Orders',
    'dashboard.pending': 'Pending',
    'dashboard.completed': 'Completed',
    'dashboard.in_progress': 'In Progress',
    'dashboard.recent_orders': 'Recent Orders',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.verify_email': 'Verify your email',
    'dashboard.verification_sent': 'Verification email sent',
    'dashboard.check_inbox': 'Check your inbox to verify your email.',
    'dashboard.no_orders': 'No orders yet',
    'dashboard.start_ordering': 'Start ordering to see your activity here',
    
    // Orders
    'orders.title': 'My Orders',
    'orders.subtitle': 'Track and manage your orders',
    'orders.pending': 'Pending',
    'orders.in_progress': 'In Progress',
    'orders.completed': 'Completed',
    'orders.cancelled': 'Cancelled',
    'orders.partial': 'Partial',
    'orders.refunded': 'Refunded',
    'orders.no_orders': 'No orders found',
    'orders.order_number': 'Order Number',
    'orders.service': 'Service',
    'orders.target_url': 'Target URL',
    'orders.progress': 'Progress',
    'orders.placed_on': 'Placed on',
    'orders.other_orders': 'Other Orders',
    'orders.search_placeholder': 'Search by order ID or service...',
    'orders.login_required': 'Login Required',
    'orders.login_to_view': 'Please sign in to view your orders.',
    
    // Services
    'services.title': 'Services',
    'services.subtitle': 'Browse and order SMM services',
    'services.categories': 'Categories',
    'services.add_to_cart': 'Add to Cart',
    'services.order_now': 'Order Now',
    'services.favorites': 'Favorites',
    'services.select_category': 'Select a category',
    'services.select_service': 'Select a service',
    'services.enter_url': 'Enter target URL',
    'services.enter_quantity': 'Enter quantity',
    'services.min_qty': 'Min',
    'services.max_qty': 'Max',
    'services.price_per_k': 'Price per 1K',
    'services.estimated_time': 'Estimated Time',
    'services.description': 'Description',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.checkout': 'Checkout All',
    'cart.total': 'Total',
    'cart.clear': 'Clear Cart',
    'cart.items': 'items',
    'cart.item': 'item',
    'cart.remove': 'Remove',
    'cart.bulk_add': 'Bulk Add',
    'cart.quick_repeat': 'Quick Repeat',
    'cart.processing': 'Processing...',
    'cart.order_placed': 'Order Placed!',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your account settings',
    'profile.balance': 'Balance',
    'profile.total_spent': 'Total Spent',
    'profile.referrals': 'Referrals',
    'profile.member_since': 'Member Since',
    'profile.change_password': 'Change Password',
    'profile.update_profile': 'Update Profile',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.mark_all_read': 'Mark all read',
    'notifications.empty': 'No notifications',
    'notifications.order_update': 'Order Update',
    'notifications.low_balance': 'Low Balance',
    'notifications.new': 'New',
    
    // Deposit / Add Funds
    'deposit.title': 'Add Funds',
    'deposit.subtitle': 'Top up your account balance',
    'deposit.amount': 'Amount',
    'deposit.method': 'Payment Method',
    'deposit.current_balance': 'Current Balance',
    'deposit.min_amount': 'Minimum amount',
    'deposit.max_amount': 'Maximum amount',
    'deposit.proceed': 'Proceed to Payment',
    
    // Support
    'support.title': 'Support',
    'support.subtitle': 'Get help with your orders',
    'support.new_ticket': 'New Ticket',
    'support.my_tickets': 'My Tickets',
    'support.faq': 'FAQ',
    'support.contact_us': 'Contact Us',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    
    // Errors
    'error.something_wrong': 'Something went wrong',
    'error.try_again': 'Please try again',
    'error.not_found': 'Not found',
    'error.unauthorized': 'Unauthorized',
    'error.loading_failed': 'Failed to load',
    'error.dashboard_unavailable': 'Dashboard temporarily unavailable',
    
    // Auth
    'auth.sign_in': 'Sign In',
    'auth.sign_up': 'Sign Up',
    'auth.sign_out': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgot_password': 'Forgot Password?',
    'auth.remember_me': 'Remember me',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.please_sign_in': 'Please Sign In',
    'auth.need_login': 'You need to be logged in to view your dashboard',
    
    // Language
    'language.title': 'Language',
    'language.select': 'Select Language',
    'language.changed': 'Language changed',
    
    // Storefront
    'storefront.nav.services': 'Services',
    'storefront.nav.features': 'Features',
    'storefront.nav.reviews': 'Reviews',
    'storefront.nav.faq': 'FAQ',
    'storefront.nav.blog': 'Blog',
    'storefront.nav.signIn': 'Sign In',
    'storefront.nav.getStarted': 'Get Started',
    'storefront.nav.dashboard': 'Dashboard',
    'storefront.nav.signOut': 'Sign Out',
    'storefront.hero.fastOrder': 'Quick Order',
    'storefront.hero.viewServices': 'Explore Services',
    'storefront.hero.trusted': 'Verified',
    'storefront.features.badge': 'Why Choose Us',
    'storefront.features.title': 'Grow Your Social Media Accounts Visibility',
    'storefront.features.paymentMethods': 'Flexible Payments',
    'storefront.features.forEveryCountry': 'worldwide options',
    'storefront.features.andMore': 'and more solutions...',
    'storefront.features.easyToUse': 'User-Friendly',
    'storefront.features.simpleProcess': 'Streamlined ordering experience',
    'storefront.features.platforms': 'Platforms',
    'storefront.features.supported': 'integrated',
    'storefront.features.discountCodes': 'Savings Available',
    'storefront.features.discountDesc': 'Apply promo codes to reduce your order costs',
    'storefront.features.support247': 'Dedicated Support',
    'storefront.features.supportDesc': 'Our team is available around the clock to assist you',
    'storefront.features.dripFeed': 'Balanced Delivery',
    'storefront.features.dripFeedDesc': 'Gradual delivery for sustainable, organic-looking results',
    'storefront.features.optimizedStart': 'Optimized Processing',
    'storefront.features.optimizedDesc': 'Orders are processed promptly with balanced pacing',
    'storefront.faq.badge': 'Common Questions',
    'storefront.faq.title': 'Your Questions, Answered',
    'storefront.faq.subtitle': 'Learn more about how our services work',
    'storefront.faq.stillQuestions': 'Need more help?',
    'storefront.faq.contactSupport': 'Reach Our Team',
    'storefront.footer.services': 'Services',
    'storefront.footer.company': 'Company',
    'storefront.footer.support': 'Support',
    'storefront.footer.aboutUs': 'About Us',
    'storefront.footer.contact': 'Contact',
    'storefront.footer.termsOfService': 'Terms of Service',
    'storefront.footer.privacyPolicy': 'Privacy Policy',
  },
  es: {
    // Navigation & Layout
    'nav.dashboard': 'Panel',
    'nav.services': 'Servicios',
    'nav.orders': 'Mis Pedidos',
    'nav.new_order': 'Nuevo Pedido',
    'nav.deposit': 'Agregar Fondos',
    'nav.support': 'Soporte',
    'nav.profile': 'Perfil',
    'nav.favorites': 'Favoritos',
    'nav.track_order': 'Rastrear Pedido',
    'nav.logout': 'Cerrar Sesión',
    'nav.menu': 'Menú',
    'nav.more': 'Más',
    'nav.blog': 'Blog',
    'nav.api': 'API',
    'nav.bulk_order': 'Pedido Masivo',
    'nav.smm_services': 'Servicios SMM',
    'nav.your_balance': 'Tu Saldo',
    'nav.language': 'Idioma',
    'nav.currency': 'Moneda',
    'nav.take_tour': 'Hacer un Tour',
    'nav.terms': 'Términos de Servicio',
    'nav.privacy': 'Política de Privacidad',
    
    // Legal pages
    'legal.table_of_contents': 'Tabla de Contenidos',
    'legal.last_updated': 'Última actualización',
    'legal.privacy_subtitle': 'Cómo recopilamos, usamos y protegemos sus datos',
    'legal.terms_subtitle': 'Por favor lea estos términos antes de usar nuestros servicios',
    'common.print': 'Imprimir',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.submit': 'Enviar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.refresh': 'Actualizar',
    'common.all': 'Todos',
    'common.view_all': 'Ver Todo',
    'common.retry': 'Reintentar',
    'common.close': 'Cerrar',
    'common.copy': 'Copiar',
    'common.copied': '¡Copiado!',
    'common.send': 'Enviar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.confirm': 'Confirmar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.details': 'Detalles',
    'common.actions': 'Acciones',
    'common.status': 'Estado',
    'common.date': 'Fecha',
    'common.price': 'Precio',
    'common.quantity': 'Cantidad',
    'common.total': 'Total',
    'common.yes': 'Sí',
    'common.no': 'No',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido de nuevo',
    'dashboard.overview': 'Resumen de tu cuenta',
    'dashboard.balance': 'Saldo',
    'dashboard.total_orders': 'Total de Pedidos',
    'dashboard.pending': 'Pendientes',
    'dashboard.completed': 'Completados',
    'dashboard.in_progress': 'En Progreso',
    'dashboard.recent_orders': 'Pedidos Recientes',
    'dashboard.quick_actions': 'Acciones Rápidas',
    'dashboard.verify_email': 'Verifica tu correo',
    'dashboard.verification_sent': 'Correo de verificación enviado',
    'dashboard.check_inbox': 'Revisa tu bandeja de entrada.',
    'dashboard.no_orders': 'Sin pedidos aún',
    'dashboard.start_ordering': 'Empieza a ordenar para ver tu actividad aquí',
    
    // Orders
    'orders.title': 'Mis Pedidos',
    'orders.subtitle': 'Rastrea y gestiona tus pedidos',
    'orders.pending': 'Pendiente',
    'orders.in_progress': 'En Progreso',
    'orders.completed': 'Completado',
    'orders.cancelled': 'Cancelado',
    'orders.partial': 'Parcial',
    'orders.refunded': 'Reembolsado',
    'orders.no_orders': 'No se encontraron pedidos',
    'orders.order_number': 'Número de Pedido',
    'orders.service': 'Servicio',
    'orders.target_url': 'URL de Destino',
    'orders.progress': 'Progreso',
    'orders.placed_on': 'Realizado el',
    'orders.other_orders': 'Otros Pedidos',
    'orders.search_placeholder': 'Buscar por ID o servicio...',
    'orders.login_required': 'Inicio de Sesión Requerido',
    'orders.login_to_view': 'Por favor inicia sesión para ver tus pedidos.',
    
    // Services
    'services.title': 'Servicios',
    'services.subtitle': 'Explora y ordena servicios SMM',
    'services.categories': 'Categorías',
    'services.add_to_cart': 'Agregar al Carrito',
    'services.order_now': 'Ordenar Ahora',
    'services.favorites': 'Favoritos',
    'services.select_category': 'Selecciona una categoría',
    'services.select_service': 'Selecciona un servicio',
    'services.enter_url': 'Ingresa la URL de destino',
    'services.enter_quantity': 'Ingresa la cantidad',
    'services.min_qty': 'Mín',
    'services.max_qty': 'Máx',
    'services.price_per_k': 'Precio por 1K',
    'services.estimated_time': 'Tiempo Estimado',
    'services.description': 'Descripción',
    
    // Cart
    'cart.title': 'Carrito de Compras',
    'cart.empty': 'Tu carrito está vacío',
    'cart.checkout': 'Pagar Todo',
    'cart.total': 'Total',
    'cart.clear': 'Vaciar Carrito',
    'cart.items': 'artículos',
    'cart.item': 'artículo',
    'cart.remove': 'Eliminar',
    'cart.bulk_add': 'Agregar Masivo',
    'cart.quick_repeat': 'Repetir Rápido',
    'cart.processing': 'Procesando...',
    'cart.order_placed': '¡Pedido Realizado!',
    
    // Profile
    'profile.title': 'Mi Perfil',
    'profile.subtitle': 'Administra tu cuenta',
    'profile.balance': 'Saldo',
    'profile.total_spent': 'Total Gastado',
    'profile.referrals': 'Referidos',
    'profile.member_since': 'Miembro Desde',
    'profile.change_password': 'Cambiar Contraseña',
    'profile.update_profile': 'Actualizar Perfil',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.mark_all_read': 'Marcar todo leído',
    'notifications.empty': 'Sin notificaciones',
    'notifications.order_update': 'Actualización de Pedido',
    'notifications.low_balance': 'Saldo Bajo',
    'notifications.new': 'Nuevo',
    
    // Deposit
    'deposit.title': 'Agregar Fondos',
    'deposit.subtitle': 'Recarga tu saldo',
    'deposit.amount': 'Cantidad',
    'deposit.method': 'Método de Pago',
    'deposit.current_balance': 'Saldo Actual',
    'deposit.min_amount': 'Cantidad mínima',
    'deposit.max_amount': 'Cantidad máxima',
    'deposit.proceed': 'Proceder al Pago',
    
    // Support
    'support.title': 'Soporte',
    'support.subtitle': 'Obtén ayuda con tus pedidos',
    'support.new_ticket': 'Nuevo Ticket',
    'support.my_tickets': 'Mis Tickets',
    'support.faq': 'Preguntas Frecuentes',
    'support.contact_us': 'Contáctanos',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    
    // Errors
    'error.something_wrong': 'Algo salió mal',
    'error.try_again': 'Por favor intenta de nuevo',
    'error.not_found': 'No encontrado',
    'error.unauthorized': 'No autorizado',
    'error.loading_failed': 'Error al cargar',
    'error.dashboard_unavailable': 'Panel temporalmente no disponible',
    
    // Auth
    'auth.sign_in': 'Iniciar Sesión',
    'auth.sign_up': 'Registrarse',
    'auth.sign_out': 'Cerrar Sesión',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.forgot_password': '¿Olvidaste tu contraseña?',
    'auth.remember_me': 'Recordarme',
    'auth.no_account': '¿No tienes cuenta?',
    'auth.have_account': '¿Ya tienes cuenta?',
    'auth.please_sign_in': 'Por favor Inicia Sesión',
    'auth.need_login': 'Debes iniciar sesión para ver tu panel',
    
    // Language
    'language.title': 'Idioma',
    'language.select': 'Seleccionar Idioma',
    'language.changed': 'Idioma cambiado',
    
    // Storefront
    'storefront.nav.services': 'Servicios',
    'storefront.nav.features': 'Características',
    'storefront.nav.reviews': 'Reseñas',
    'storefront.nav.faq': 'Preguntas',
    'storefront.nav.blog': 'Blog',
    'storefront.nav.signIn': 'Iniciar Sesión',
    'storefront.nav.getStarted': 'Comenzar',
    'storefront.nav.dashboard': 'Panel',
    'storefront.nav.signOut': 'Cerrar Sesión',
    'storefront.hero.fastOrder': 'Pedido Rápido',
    'storefront.hero.viewServices': 'Explorar Servicios',
    'storefront.hero.trusted': 'Verificado',
    'storefront.features.badge': 'Por Qué Elegirnos',
    'storefront.features.title': 'Mejora la Visibilidad de tus Redes Sociales',
    'storefront.features.paymentMethods': 'Pagos Flexibles',
    'storefront.features.forEveryCountry': 'opciones mundiales',
    'storefront.features.andMore': 'y más soluciones...',
    'storefront.features.easyToUse': 'Fácil de Usar',
    'storefront.features.simpleProcess': 'Experiencia de pedido simplificada',
    'storefront.features.platforms': 'Plataformas',
    'storefront.features.supported': 'integradas',
    'storefront.features.discountCodes': 'Ahorros Disponibles',
    'storefront.features.discountDesc': 'Aplica códigos promocionales para reducir costos',
    'storefront.features.support247': 'Soporte Dedicado',
    'storefront.features.supportDesc': 'Nuestro equipo está disponible para asistirte',
    'storefront.features.dripFeed': 'Entrega Equilibrada',
    'storefront.features.dripFeedDesc': 'Entrega gradual para resultados sostenibles',
    'storefront.features.optimizedStart': 'Procesamiento Optimizado',
    'storefront.features.optimizedDesc': 'Los pedidos se procesan con ritmo equilibrado',
    'storefront.faq.badge': 'Preguntas Comunes',
    'storefront.faq.title': 'Tus Preguntas, Respondidas',
    'storefront.faq.subtitle': 'Conoce más sobre cómo funcionan nuestros servicios',
    'storefront.faq.stillQuestions': '¿Necesitas más ayuda?',
    'storefront.faq.contactSupport': 'Contactar Equipo',
    'storefront.footer.services': 'Servicios',
    'storefront.footer.company': 'Empresa',
    'storefront.footer.support': 'Soporte',
    'storefront.footer.aboutUs': 'Sobre Nosotros',
    'storefront.footer.contact': 'Contacto',
    'storefront.footer.termsOfService': 'Términos de Servicio',
    'storefront.footer.privacyPolicy': 'Política de Privacidad',
  },
  pt: {
    'nav.dashboard': 'Painel',
    'nav.services': 'Serviços',
    'nav.orders': 'Meus Pedidos',
    'nav.new_order': 'Novo Pedido',
    'nav.deposit': 'Adicionar Fundos',
    'nav.support': 'Suporte',
    'nav.profile': 'Perfil',
    'nav.favorites': 'Favoritos',
    'nav.track_order': 'Rastrear Pedido',
    'nav.logout': 'Sair',
    'nav.menu': 'Menu',
    'nav.more': 'Mais',
    'nav.blog': 'Blog',
    'nav.api': 'API',
    'nav.bulk_order': 'Pedido em Massa',
    'nav.smm_services': 'Serviços SMM',
    'nav.your_balance': 'Seu Saldo',
    'nav.language': 'Idioma',
    'nav.currency': 'Moeda',
    'nav.take_tour': 'Fazer um Tour',
    'nav.terms': 'Termos de Serviço',
    'nav.privacy': 'Política de Privacidade',
    
    // Legal pages
    'legal.table_of_contents': 'Índice',
    'legal.last_updated': 'Última atualização',
    'legal.privacy_subtitle': 'Como coletamos, usamos e protegemos seus dados',
    'legal.terms_subtitle': 'Por favor leia estes termos antes de usar nossos serviços',
    'common.print': 'Imprimir',
    'common.loading': 'Carregando...',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.submit': 'Enviar',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.refresh': 'Atualizar',
    'common.all': 'Todos',
    'common.view_all': 'Ver Tudo',
    'common.retry': 'Tentar Novamente',
    'common.close': 'Fechar',
    'common.copy': 'Copiar',
    'common.copied': 'Copiado!',
    'common.send': 'Enviar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.confirm': 'Confirmar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.details': 'Detalhes',
    'common.actions': 'Ações',
    'common.status': 'Status',
    'common.date': 'Data',
    'common.price': 'Preço',
    'common.quantity': 'Quantidade',
    'common.total': 'Total',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'dashboard.welcome': 'Bem-vindo de volta',
    'dashboard.overview': 'Visão geral da sua conta',
    'dashboard.balance': 'Saldo',
    'dashboard.total_orders': 'Total de Pedidos',
    'dashboard.pending': 'Pendentes',
    'dashboard.completed': 'Concluídos',
    'dashboard.in_progress': 'Em Progresso',
    'dashboard.recent_orders': 'Pedidos Recentes',
    'dashboard.quick_actions': 'Ações Rápidas',
    'dashboard.verify_email': 'Verifique seu email',
    'dashboard.verification_sent': 'Email de verificação enviado',
    'dashboard.check_inbox': 'Verifique sua caixa de entrada.',
    'dashboard.no_orders': 'Sem pedidos ainda',
    'dashboard.start_ordering': 'Comece a fazer pedidos para ver sua atividade aqui',
    'orders.title': 'Meus Pedidos',
    'orders.subtitle': 'Acompanhe e gerencie seus pedidos',
    'orders.pending': 'Pendente',
    'orders.in_progress': 'Em Progresso',
    'orders.completed': 'Concluído',
    'orders.cancelled': 'Cancelado',
    'orders.partial': 'Parcial',
    'orders.refunded': 'Reembolsado',
    'orders.no_orders': 'Nenhum pedido encontrado',
    'orders.order_number': 'Número do Pedido',
    'orders.service': 'Serviço',
    'orders.target_url': 'URL de Destino',
    'orders.progress': 'Progresso',
    'orders.placed_on': 'Realizado em',
    'orders.other_orders': 'Outros Pedidos',
    'orders.search_placeholder': 'Buscar por ID ou serviço...',
    'orders.login_required': 'Login Necessário',
    'orders.login_to_view': 'Por favor faça login para ver seus pedidos.',
    'services.title': 'Serviços',
    'services.subtitle': 'Navegue e peça serviços SMM',
    'services.categories': 'Categorias',
    'services.add_to_cart': 'Adicionar ao Carrinho',
    'services.order_now': 'Pedir Agora',
    'services.favorites': 'Favoritos',
    'services.select_category': 'Selecione uma categoria',
    'services.select_service': 'Selecione um serviço',
    'services.enter_url': 'Digite a URL de destino',
    'services.enter_quantity': 'Digite a quantidade',
    'services.min_qty': 'Mín',
    'services.max_qty': 'Máx',
    'services.price_per_k': 'Preço por 1K',
    'services.estimated_time': 'Tempo Estimado',
    'services.description': 'Descrição',
    'cart.title': 'Carrinho de Compras',
    'cart.empty': 'Seu carrinho está vazio',
    'cart.checkout': 'Finalizar Compra',
    'cart.total': 'Total',
    'cart.clear': 'Limpar Carrinho',
    'cart.items': 'itens',
    'cart.item': 'item',
    'cart.remove': 'Remover',
    'cart.bulk_add': 'Adicionar em Massa',
    'cart.quick_repeat': 'Repetir Rápido',
    'cart.processing': 'Processando...',
    'cart.order_placed': 'Pedido Realizado!',
    'profile.title': 'Meu Perfil',
    'profile.subtitle': 'Gerencie suas configurações',
    'profile.balance': 'Saldo',
    'profile.total_spent': 'Total Gasto',
    'profile.referrals': 'Indicações',
    'profile.member_since': 'Membro Desde',
    'profile.change_password': 'Alterar Senha',
    'profile.update_profile': 'Atualizar Perfil',
    'notifications.title': 'Notificações',
    'notifications.mark_all_read': 'Marcar tudo como lido',
    'notifications.empty': 'Sem notificações',
    'notifications.order_update': 'Atualização do Pedido',
    'notifications.low_balance': 'Saldo Baixo',
    'notifications.new': 'Novo',
    'deposit.title': 'Adicionar Fundos',
    'deposit.subtitle': 'Recarregue seu saldo',
    'deposit.amount': 'Valor',
    'deposit.method': 'Método de Pagamento',
    'deposit.current_balance': 'Saldo Atual',
    'deposit.min_amount': 'Valor mínimo',
    'deposit.max_amount': 'Valor máximo',
    'deposit.proceed': 'Prosseguir para Pagamento',
    'support.title': 'Suporte',
    'support.subtitle': 'Obtenha ajuda com seus pedidos',
    'support.new_ticket': 'Novo Ticket',
    'support.my_tickets': 'Meus Tickets',
    'support.faq': 'Perguntas Frequentes',
    'support.contact_us': 'Fale Conosco',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'error.something_wrong': 'Algo deu errado',
    'error.try_again': 'Por favor tente novamente',
    'error.not_found': 'Não encontrado',
    'error.unauthorized': 'Não autorizado',
    'error.loading_failed': 'Falha ao carregar',
    'error.dashboard_unavailable': 'Painel temporariamente indisponível',
    'auth.sign_in': 'Entrar',
    'auth.sign_up': 'Cadastrar',
    'auth.sign_out': 'Sair',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.forgot_password': 'Esqueceu a senha?',
    'auth.remember_me': 'Lembrar-me',
    'auth.no_account': 'Não tem conta?',
    'auth.have_account': 'Já tem conta?',
    'auth.please_sign_in': 'Por favor faça login',
    'auth.need_login': 'Você precisa estar logado para ver seu painel',
    'language.title': 'Idioma',
    'language.select': 'Selecionar Idioma',
    'language.changed': 'Idioma alterado',
    
    // Storefront
    'storefront.nav.services': 'Serviços',
    'storefront.nav.features': 'Recursos',
    'storefront.nav.reviews': 'Avaliações',
    'storefront.nav.faq': 'FAQ',
    'storefront.nav.blog': 'Blog',
    'storefront.nav.signIn': 'Entrar',
    'storefront.nav.getStarted': 'Começar',
    'storefront.nav.dashboard': 'Painel',
    'storefront.nav.signOut': 'Sair',
    'storefront.hero.fastOrder': 'Pedido Rápido',
    'storefront.hero.viewServices': 'Explorar Serviços',
    'storefront.hero.trusted': 'Verificado',
    'storefront.features.badge': 'Por Que Nos Escolher',
    'storefront.features.title': 'Aumente a Visibilidade das Suas Redes Sociais',
    'storefront.features.paymentMethods': 'Pagamentos Flexíveis',
    'storefront.features.forEveryCountry': 'opções mundiais',
    'storefront.features.andMore': 'e mais soluções...',
    'storefront.features.easyToUse': 'Fácil de Usar',
    'storefront.features.simpleProcess': 'Experiência de pedido simplificada',
    'storefront.features.platforms': 'Plataformas',
    'storefront.features.supported': 'integradas',
    'storefront.features.discountCodes': 'Economia Disponível',
    'storefront.features.discountDesc': 'Aplique códigos promocionais para reduzir custos',
    'storefront.features.support247': 'Suporte Dedicado',
    'storefront.features.supportDesc': 'Nossa equipe está disponível para ajudá-lo',
    'storefront.features.dripFeed': 'Entrega Equilibrada',
    'storefront.features.dripFeedDesc': 'Entrega gradual para resultados sustentáveis',
    'storefront.features.optimizedStart': 'Processamento Otimizado',
    'storefront.features.optimizedDesc': 'Pedidos processados com ritmo equilibrado',
    'storefront.faq.badge': 'Perguntas Comuns',
    'storefront.faq.title': 'Suas Perguntas, Respondidas',
    'storefront.faq.subtitle': 'Saiba mais sobre como nossos serviços funcionam',
    'storefront.faq.stillQuestions': 'Precisa de mais ajuda?',
    'storefront.faq.contactSupport': 'Contatar Equipe',
    'storefront.footer.services': 'Serviços',
    'storefront.footer.company': 'Empresa',
    'storefront.footer.support': 'Suporte',
    'storefront.footer.aboutUs': 'Sobre Nós',
    'storefront.footer.contact': 'Contato',
    'storefront.footer.termsOfService': 'Termos de Serviço',
    'storefront.footer.privacyPolicy': 'Política de Privacidade',
  },
  ar: {
    'nav.dashboard': 'لوحة التحكم',
    'nav.services': 'الخدمات',
    'nav.orders': 'طلباتي',
    'nav.new_order': 'طلب جديد',
    'nav.deposit': 'إضافة رصيد',
    'nav.support': 'الدعم',
    'nav.profile': 'الملف الشخصي',
    'nav.favorites': 'المفضلة',
    'nav.track_order': 'تتبع الطلب',
    'nav.logout': 'تسجيل الخروج',
    'nav.menu': 'القائمة',
    'nav.more': 'المزيد',
    'nav.blog': 'المدونة',
    'nav.api': 'واجهة برمجة',
    'nav.bulk_order': 'طلب جماعي',
    'nav.smm_services': 'خدمات SMM',
    'nav.your_balance': 'رصيدك',
    'nav.language': 'اللغة',
    'nav.currency': 'العملة',
    'nav.take_tour': 'قم بجولة',
    'nav.terms': 'شروط الخدمة',
    'nav.privacy': 'سياسة الخصوصية',
    
    // Legal pages
    'legal.table_of_contents': 'جدول المحتويات',
    'legal.last_updated': 'آخر تحديث',
    'legal.privacy_subtitle': 'كيف نجمع ونستخدم ونحمي بياناتك',
    'legal.terms_subtitle': 'يرجى قراءة هذه الشروط قبل استخدام خدماتنا',
    'common.print': 'طباعة',
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.submit': 'إرسال',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.refresh': 'تحديث',
    'common.all': 'الكل',
    'common.view_all': 'عرض الكل',
    'common.retry': 'إعادة المحاولة',
    'common.close': 'إغلاق',
    'common.copy': 'نسخ',
    'common.copied': 'تم النسخ!',
    'common.send': 'إرسال',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.confirm': 'تأكيد',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.details': 'التفاصيل',
    'common.actions': 'الإجراءات',
    'common.status': 'الحالة',
    'common.date': 'التاريخ',
    'common.price': 'السعر',
    'common.quantity': 'الكمية',
    'common.total': 'المجموع',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.overview': 'نظرة عامة على حسابك',
    'dashboard.balance': 'الرصيد',
    'dashboard.total_orders': 'إجمالي الطلبات',
    'dashboard.pending': 'قيد الانتظار',
    'dashboard.completed': 'مكتملة',
    'dashboard.in_progress': 'قيد التنفيذ',
    'dashboard.recent_orders': 'الطلبات الأخيرة',
    'dashboard.quick_actions': 'إجراءات سريعة',
    'dashboard.verify_email': 'تحقق من بريدك',
    'dashboard.verification_sent': 'تم إرسال بريد التحقق',
    'dashboard.check_inbox': 'تحقق من صندوق الوارد.',
    'dashboard.no_orders': 'لا توجد طلبات بعد',
    'dashboard.start_ordering': 'ابدأ بالطلب لرؤية نشاطك هنا',
    'orders.title': 'طلباتي',
    'orders.subtitle': 'تتبع وإدارة طلباتك',
    'orders.pending': 'قيد الانتظار',
    'orders.in_progress': 'قيد التنفيذ',
    'orders.completed': 'مكتمل',
    'orders.cancelled': 'ملغي',
    'orders.partial': 'جزئي',
    'orders.refunded': 'مسترد',
    'orders.no_orders': 'لا توجد طلبات',
    'orders.order_number': 'رقم الطلب',
    'orders.service': 'الخدمة',
    'orders.target_url': 'رابط الهدف',
    'orders.progress': 'التقدم',
    'orders.placed_on': 'تم الطلب في',
    'orders.other_orders': 'طلبات أخرى',
    'orders.search_placeholder': 'البحث برقم الطلب أو الخدمة...',
    'orders.login_required': 'تسجيل الدخول مطلوب',
    'orders.login_to_view': 'يرجى تسجيل الدخول لعرض طلباتك.',
    'services.title': 'الخدمات',
    'services.subtitle': 'تصفح واطلب خدمات SMM',
    'services.categories': 'الفئات',
    'services.add_to_cart': 'أضف إلى السلة',
    'services.order_now': 'اطلب الآن',
    'services.favorites': 'المفضلة',
    'services.select_category': 'اختر فئة',
    'services.select_service': 'اختر خدمة',
    'services.enter_url': 'أدخل رابط الهدف',
    'services.enter_quantity': 'أدخل الكمية',
    'services.min_qty': 'الحد الأدنى',
    'services.max_qty': 'الحد الأقصى',
    'services.price_per_k': 'السعر لكل 1000',
    'services.estimated_time': 'الوقت المتوقع',
    'services.description': 'الوصف',
    'cart.title': 'سلة التسوق',
    'cart.empty': 'سلتك فارغة',
    'cart.checkout': 'إتمام الشراء',
    'cart.total': 'المجموع',
    'cart.clear': 'إفراغ السلة',
    'cart.items': 'عناصر',
    'cart.item': 'عنصر',
    'cart.remove': 'إزالة',
    'cart.bulk_add': 'إضافة جماعية',
    'cart.quick_repeat': 'تكرار سريع',
    'cart.processing': 'جاري المعالجة...',
    'cart.order_placed': 'تم الطلب!',
    'profile.title': 'ملفي الشخصي',
    'profile.subtitle': 'إدارة إعدادات حسابك',
    'profile.balance': 'الرصيد',
    'profile.total_spent': 'إجمالي الإنفاق',
    'profile.referrals': 'الإحالات',
    'profile.member_since': 'عضو منذ',
    'profile.change_password': 'تغيير كلمة المرور',
    'profile.update_profile': 'تحديث الملف',
    'notifications.title': 'الإشعارات',
    'notifications.mark_all_read': 'تحديد الكل كمقروء',
    'notifications.empty': 'لا توجد إشعارات',
    'notifications.order_update': 'تحديث الطلب',
    'notifications.low_balance': 'رصيد منخفض',
    'notifications.new': 'جديد',
    'deposit.title': 'إضافة رصيد',
    'deposit.subtitle': 'شحن رصيد حسابك',
    'deposit.amount': 'المبلغ',
    'deposit.method': 'طريقة الدفع',
    'deposit.current_balance': 'الرصيد الحالي',
    'deposit.min_amount': 'الحد الأدنى',
    'deposit.max_amount': 'الحد الأقصى',
    'deposit.proceed': 'المتابعة للدفع',
    'support.title': 'الدعم',
    'support.subtitle': 'احصل على مساعدة لطلباتك',
    'support.new_ticket': 'تذكرة جديدة',
    'support.my_tickets': 'تذاكري',
    'support.faq': 'الأسئلة الشائعة',
    'support.contact_us': 'تواصل معنا',
    'support.whatsapp': 'واتساب',
    'support.telegram': 'تيليجرام',
    'error.something_wrong': 'حدث خطأ',
    'error.try_again': 'يرجى المحاولة مجدداً',
    'error.not_found': 'غير موجود',
    'error.unauthorized': 'غير مصرح',
    'error.loading_failed': 'فشل التحميل',
    'error.dashboard_unavailable': 'لوحة التحكم غير متاحة مؤقتاً',
    'auth.sign_in': 'تسجيل الدخول',
    'auth.sign_up': 'إنشاء حساب',
    'auth.sign_out': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgot_password': 'نسيت كلمة المرور؟',
    'auth.remember_me': 'تذكرني',
    'auth.no_account': 'ليس لديك حساب؟',
    'auth.have_account': 'لديك حساب بالفعل؟',
    'auth.please_sign_in': 'يرجى تسجيل الدخول',
    'auth.need_login': 'يجب تسجيل الدخول لعرض لوحة التحكم',
    'language.title': 'اللغة',
    'language.select': 'اختر اللغة',
    'language.changed': 'تم تغيير اللغة',
    
    // Storefront
    'storefront.nav.services': 'الخدمات',
    'storefront.nav.features': 'المميزات',
    'storefront.nav.reviews': 'التقييمات',
    'storefront.nav.faq': 'الأسئلة الشائعة',
    'storefront.nav.blog': 'المدونة',
    'storefront.nav.signIn': 'تسجيل الدخول',
    'storefront.nav.getStarted': 'ابدأ الآن',
    'storefront.nav.dashboard': 'لوحة التحكم',
    'storefront.nav.signOut': 'تسجيل الخروج',
    'storefront.hero.fastOrder': 'طلب سريع',
    'storefront.hero.viewServices': 'استكشف الخدمات',
    'storefront.hero.trusted': 'موثق',
    'storefront.features.badge': 'لماذا تختارنا',
    'storefront.features.title': 'عزز ظهور حساباتك على وسائل التواصل',
    'storefront.features.paymentMethods': 'دفع مرن',
    'storefront.features.forEveryCountry': 'خيارات عالمية',
    'storefront.features.andMore': 'وحلول أخرى...',
    'storefront.features.easyToUse': 'سهل الاستخدام',
    'storefront.features.simpleProcess': 'تجربة طلب مبسطة',
    'storefront.features.platforms': 'المنصات',
    'storefront.features.supported': 'متكاملة',
    'storefront.features.discountCodes': 'توفير متاح',
    'storefront.features.discountDesc': 'طبق أكواد الخصم لتقليل التكاليف',
    'storefront.features.support247': 'دعم مخصص',
    'storefront.features.supportDesc': 'فريقنا متاح على مدار الساعة لمساعدتك',
    'storefront.features.dripFeed': 'تسليم متوازن',
    'storefront.features.dripFeedDesc': 'تسليم تدريجي لنتائج مستدامة',
    'storefront.features.optimizedStart': 'معالجة محسنة',
    'storefront.features.optimizedDesc': 'تتم معالجة الطلبات بإيقاع متوازن',
    'storefront.faq.badge': 'أسئلة شائعة',
    'storefront.faq.title': 'أسئلتك، مُجابة',
    'storefront.faq.subtitle': 'تعرف على كيفية عمل خدماتنا',
    'storefront.faq.stillQuestions': 'تحتاج مزيد من المساعدة؟',
    'storefront.faq.contactSupport': 'تواصل مع فريقنا',
    'storefront.footer.services': 'الخدمات',
    'storefront.footer.company': 'الشركة',
    'storefront.footer.support': 'الدعم',
    'storefront.footer.aboutUs': 'من نحن',
    'storefront.footer.contact': 'تواصل معنا',
    'storefront.footer.termsOfService': 'شروط الخدمة',
    'storefront.footer.privacyPolicy': 'سياسة الخصوصية',
  },
  tr: {
    'nav.dashboard': 'Panel',
    'nav.services': 'Hizmetler',
    'nav.orders': 'Siparişlerim',
    'nav.new_order': 'Yeni Sipariş',
    'nav.deposit': 'Bakiye Ekle',
    'nav.support': 'Destek',
    'nav.profile': 'Profil',
    'nav.favorites': 'Favoriler',
    'nav.track_order': 'Sipariş Takip',
    'nav.logout': 'Çıkış Yap',
    'nav.menu': 'Menü',
    'nav.more': 'Daha Fazla',
    'nav.blog': 'Blog',
    'nav.api': 'API',
    'nav.bulk_order': 'Toplu Sipariş',
    'nav.smm_services': 'SMM Hizmetleri',
    'nav.your_balance': 'Bakiyeniz',
    'common.loading': 'Yükleniyor...',
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.submit': 'Gönder',
    'common.search': 'Ara',
    'common.filter': 'Filtrele',
    'common.export': 'Dışa Aktar',
    'common.refresh': 'Yenile',
    'common.all': 'Tümü',
    'common.view_all': 'Tümünü Gör',
    'common.retry': 'Tekrar Dene',
    'common.close': 'Kapat',
    'common.copy': 'Kopyala',
    'common.copied': 'Kopyalandı!',
    'common.send': 'Gönder',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.confirm': 'Onayla',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.view': 'Görüntüle',
    'common.details': 'Detaylar',
    'common.actions': 'İşlemler',
    'common.status': 'Durum',
    'common.date': 'Tarih',
    'common.price': 'Fiyat',
    'common.quantity': 'Miktar',
    'common.total': 'Toplam',
    'common.yes': 'Evet',
    'common.no': 'Hayır',
    'dashboard.welcome': 'Tekrar hoş geldiniz',
    'dashboard.overview': 'Hesap özetiniz',
    'dashboard.balance': 'Bakiye',
    'dashboard.total_orders': 'Toplam Sipariş',
    'dashboard.pending': 'Bekleyen',
    'dashboard.completed': 'Tamamlanan',
    'dashboard.in_progress': 'İşleniyor',
    'dashboard.recent_orders': 'Son Siparişler',
    'dashboard.quick_actions': 'Hızlı İşlemler',
    'dashboard.verify_email': 'E-postanızı doğrulayın',
    'dashboard.verification_sent': 'Doğrulama e-postası gönderildi',
    'dashboard.check_inbox': 'Gelen kutunuzu kontrol edin.',
    'dashboard.no_orders': 'Henüz sipariş yok',
    'dashboard.start_ordering': 'Aktivitenizi görmek için sipariş vermeye başlayın',
    'orders.title': 'Siparişlerim',
    'orders.subtitle': 'Siparişlerinizi takip edin',
    'orders.pending': 'Beklemede',
    'orders.in_progress': 'İşleniyor',
    'orders.completed': 'Tamamlandı',
    'orders.cancelled': 'İptal Edildi',
    'orders.partial': 'Kısmi',
    'orders.refunded': 'İade Edildi',
    'orders.no_orders': 'Sipariş bulunamadı',
    'orders.order_number': 'Sipariş Numarası',
    'orders.service': 'Hizmet',
    'orders.target_url': 'Hedef URL',
    'orders.progress': 'İlerleme',
    'orders.placed_on': 'Sipariş Tarihi',
    'orders.other_orders': 'Diğer Siparişler',
    'orders.search_placeholder': 'ID veya hizmet ara...',
    'orders.login_required': 'Giriş Gerekli',
    'orders.login_to_view': 'Siparişlerinizi görmek için giriş yapın.',
    'services.title': 'Hizmetler',
    'services.subtitle': 'SMM hizmetlerini keşfedin',
    'services.categories': 'Kategoriler',
    'services.add_to_cart': 'Sepete Ekle',
    'services.order_now': 'Şimdi Sipariş Ver',
    'services.favorites': 'Favoriler',
    'services.select_category': 'Kategori seçin',
    'services.select_service': 'Hizmet seçin',
    'services.enter_url': 'Hedef URL girin',
    'services.enter_quantity': 'Miktar girin',
    'services.min_qty': 'Min',
    'services.max_qty': 'Maks',
    'services.price_per_k': '1K Fiyatı',
    'services.estimated_time': 'Tahmini Süre',
    'services.description': 'Açıklama',
    'cart.title': 'Alışveriş Sepeti',
    'cart.empty': 'Sepetiniz boş',
    'cart.checkout': 'Ödeme Yap',
    'cart.total': 'Toplam',
    'cart.clear': 'Sepeti Temizle',
    'cart.items': 'ürün',
    'cart.item': 'ürün',
    'cart.remove': 'Kaldır',
    'cart.bulk_add': 'Toplu Ekle',
    'cart.quick_repeat': 'Hızlı Tekrar',
    'cart.processing': 'İşleniyor...',
    'cart.order_placed': 'Sipariş Verildi!',
    'profile.title': 'Profilim',
    'profile.subtitle': 'Hesap ayarlarını yönet',
    'profile.balance': 'Bakiye',
    'profile.total_spent': 'Toplam Harcama',
    'profile.referrals': 'Referanslar',
    'profile.member_since': 'Üyelik Tarihi',
    'profile.change_password': 'Şifre Değiştir',
    'profile.update_profile': 'Profili Güncelle',
    'notifications.title': 'Bildirimler',
    'notifications.mark_all_read': 'Tümünü okundu işaretle',
    'notifications.empty': 'Bildirim yok',
    'notifications.order_update': 'Sipariş Güncellemesi',
    'notifications.low_balance': 'Düşük Bakiye',
    'notifications.new': 'Yeni',
    'deposit.title': 'Bakiye Ekle',
    'deposit.subtitle': 'Hesabınızı yükleyin',
    'deposit.amount': 'Tutar',
    'deposit.method': 'Ödeme Yöntemi',
    'deposit.current_balance': 'Mevcut Bakiye',
    'deposit.min_amount': 'Minimum tutar',
    'deposit.max_amount': 'Maksimum tutar',
    'deposit.proceed': 'Ödemeye Devam Et',
    'support.title': 'Destek',
    'support.subtitle': 'Siparişleriniz için yardım alın',
    'support.new_ticket': 'Yeni Destek Talebi',
    'support.my_tickets': 'Destek Taleplerim',
    'support.faq': 'SSS',
    'support.contact_us': 'Bize Ulaşın',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'error.something_wrong': 'Bir şeyler yanlış gitti',
    'error.try_again': 'Lütfen tekrar deneyin',
    'error.not_found': 'Bulunamadı',
    'error.unauthorized': 'Yetkisiz',
    'error.loading_failed': 'Yükleme başarısız',
    'error.dashboard_unavailable': 'Panel geçici olarak kullanılamıyor',
    'auth.sign_in': 'Giriş Yap',
    'auth.sign_up': 'Kayıt Ol',
    'auth.sign_out': 'Çıkış Yap',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.forgot_password': 'Şifremi unuttum',
    'auth.remember_me': 'Beni hatırla',
    'auth.no_account': 'Hesabınız yok mu?',
    'auth.have_account': 'Zaten hesabınız var mı?',
    'auth.please_sign_in': 'Lütfen giriş yapın',
    'auth.need_login': 'Panelinizi görmek için giriş yapmalısınız',
    'language.title': 'Dil',
    'language.select': 'Dil Seçin',
    'language.changed': 'Dil değiştirildi',
  },
  ru: {
    'nav.dashboard': 'Панель',
    'nav.services': 'Услуги',
    'nav.orders': 'Мои заказы',
    'nav.new_order': 'Новый заказ',
    'nav.deposit': 'Пополнить',
    'nav.support': 'Поддержка',
    'nav.profile': 'Профиль',
    'nav.favorites': 'Избранное',
    'nav.track_order': 'Отследить заказ',
    'nav.logout': 'Выход',
    'nav.menu': 'Меню',
    'nav.more': 'Ещё',
    'nav.blog': 'Блог',
    'nav.api': 'API',
    'nav.bulk_order': 'Массовый заказ',
    'nav.smm_services': 'SMM услуги',
    'nav.your_balance': 'Ваш баланс',
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.submit': 'Отправить',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.export': 'Экспорт',
    'common.refresh': 'Обновить',
    'common.all': 'Все',
    'common.view_all': 'Показать все',
    'common.retry': 'Повторить',
    'common.close': 'Закрыть',
    'common.copy': 'Копировать',
    'common.copied': 'Скопировано!',
    'common.send': 'Отправить',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.confirm': 'Подтвердить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.view': 'Просмотр',
    'common.details': 'Подробности',
    'common.actions': 'Действия',
    'common.status': 'Статус',
    'common.date': 'Дата',
    'common.price': 'Цена',
    'common.quantity': 'Количество',
    'common.total': 'Итого',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'dashboard.welcome': 'С возвращением',
    'dashboard.overview': 'Обзор вашего аккаунта',
    'dashboard.balance': 'Баланс',
    'dashboard.total_orders': 'Всего заказов',
    'dashboard.pending': 'Ожидают',
    'dashboard.completed': 'Завершены',
    'dashboard.in_progress': 'В процессе',
    'dashboard.recent_orders': 'Последние заказы',
    'dashboard.quick_actions': 'Быстрые действия',
    'dashboard.verify_email': 'Подтвердите email',
    'dashboard.verification_sent': 'Письмо отправлено',
    'dashboard.check_inbox': 'Проверьте почту.',
    'dashboard.no_orders': 'Заказов пока нет',
    'dashboard.start_ordering': 'Начните заказывать, чтобы увидеть активность',
    'orders.title': 'Мои заказы',
    'orders.subtitle': 'Отслеживайте свои заказы',
    'orders.pending': 'Ожидает',
    'orders.in_progress': 'В процессе',
    'orders.completed': 'Завершён',
    'orders.cancelled': 'Отменён',
    'orders.partial': 'Частичный',
    'orders.refunded': 'Возвращён',
    'orders.no_orders': 'Заказы не найдены',
    'orders.order_number': 'Номер заказа',
    'orders.service': 'Услуга',
    'orders.target_url': 'Целевой URL',
    'orders.progress': 'Прогресс',
    'orders.placed_on': 'Создан',
    'orders.other_orders': 'Другие заказы',
    'orders.search_placeholder': 'Поиск по ID или услуге...',
    'orders.login_required': 'Требуется вход',
    'orders.login_to_view': 'Войдите, чтобы просмотреть заказы.',
    'services.title': 'Услуги',
    'services.subtitle': 'Просмотр и заказ SMM услуг',
    'services.categories': 'Категории',
    'services.add_to_cart': 'В корзину',
    'services.order_now': 'Заказать',
    'services.favorites': 'Избранное',
    'services.select_category': 'Выберите категорию',
    'services.select_service': 'Выберите услугу',
    'services.enter_url': 'Введите URL',
    'services.enter_quantity': 'Введите количество',
    'services.min_qty': 'Мин',
    'services.max_qty': 'Макс',
    'services.price_per_k': 'Цена за 1К',
    'services.estimated_time': 'Примерное время',
    'services.description': 'Описание',
    'cart.title': 'Корзина',
    'cart.empty': 'Корзина пуста',
    'cart.checkout': 'Оформить заказ',
    'cart.total': 'Итого',
    'cart.clear': 'Очистить',
    'cart.items': 'товаров',
    'cart.item': 'товар',
    'cart.remove': 'Удалить',
    'cart.bulk_add': 'Массовое добавление',
    'cart.quick_repeat': 'Быстрый повтор',
    'cart.processing': 'Обработка...',
    'cart.order_placed': 'Заказ оформлен!',
    'profile.title': 'Мой профиль',
    'profile.subtitle': 'Управление настройками',
    'profile.balance': 'Баланс',
    'profile.total_spent': 'Всего потрачено',
    'profile.referrals': 'Рефералы',
    'profile.member_since': 'Участник с',
    'profile.change_password': 'Сменить пароль',
    'profile.update_profile': 'Обновить профиль',
    'notifications.title': 'Уведомления',
    'notifications.mark_all_read': 'Прочитать все',
    'notifications.empty': 'Нет уведомлений',
    'notifications.order_update': 'Обновление заказа',
    'notifications.low_balance': 'Низкий баланс',
    'notifications.new': 'Новое',
    'deposit.title': 'Пополнить',
    'deposit.subtitle': 'Пополните баланс',
    'deposit.amount': 'Сумма',
    'deposit.method': 'Способ оплаты',
    'deposit.current_balance': 'Текущий баланс',
    'deposit.min_amount': 'Минимальная сумма',
    'deposit.max_amount': 'Максимальная сумма',
    'deposit.proceed': 'Перейти к оплате',
    'support.title': 'Поддержка',
    'support.subtitle': 'Помощь с заказами',
    'support.new_ticket': 'Новый тикет',
    'support.my_tickets': 'Мои тикеты',
    'support.faq': 'ЧаВо',
    'support.contact_us': 'Связаться',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'error.something_wrong': 'Что-то пошло не так',
    'error.try_again': 'Попробуйте снова',
    'error.not_found': 'Не найдено',
    'error.unauthorized': 'Не авторизован',
    'error.loading_failed': 'Ошибка загрузки',
    'error.dashboard_unavailable': 'Панель временно недоступна',
    'auth.sign_in': 'Войти',
    'auth.sign_up': 'Регистрация',
    'auth.sign_out': 'Выйти',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.forgot_password': 'Забыли пароль?',
    'auth.remember_me': 'Запомнить меня',
    'auth.no_account': 'Нет аккаунта?',
    'auth.have_account': 'Уже есть аккаунт?',
    'auth.please_sign_in': 'Пожалуйста, войдите',
    'auth.need_login': 'Войдите для просмотра панели',
    'language.title': 'Язык',
    'language.select': 'Выбрать язык',
    'language.changed': 'Язык изменён',
  },
  fr: {
    'nav.dashboard': 'Tableau de bord',
    'nav.services': 'Services',
    'nav.orders': 'Mes Commandes',
    'nav.new_order': 'Nouvelle Commande',
    'nav.deposit': 'Ajouter des Fonds',
    'nav.support': 'Support',
    'nav.profile': 'Profil',
    'nav.favorites': 'Favoris',
    'nav.track_order': 'Suivre Commande',
    'nav.logout': 'Déconnexion',
    'nav.menu': 'Menu',
    'nav.more': 'Plus',
    'nav.blog': 'Blog',
    'nav.api': 'API',
    'nav.bulk_order': 'Commande Groupée',
    'nav.smm_services': 'Services SMM',
    'nav.your_balance': 'Votre Solde',
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.submit': 'Soumettre',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.refresh': 'Actualiser',
    'common.all': 'Tout',
    'common.view_all': 'Voir Tout',
    'common.retry': 'Réessayer',
    'common.close': 'Fermer',
    'common.copy': 'Copier',
    'common.copied': 'Copié!',
    'common.send': 'Envoyer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.confirm': 'Confirmer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.details': 'Détails',
    'common.actions': 'Actions',
    'common.status': 'Statut',
    'common.date': 'Date',
    'common.price': 'Prix',
    'common.quantity': 'Quantité',
    'common.total': 'Total',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'dashboard.welcome': 'Bon retour',
    'dashboard.overview': 'Aperçu de votre compte',
    'dashboard.balance': 'Solde',
    'dashboard.total_orders': 'Total Commandes',
    'dashboard.pending': 'En Attente',
    'dashboard.completed': 'Terminées',
    'dashboard.in_progress': 'En Cours',
    'dashboard.recent_orders': 'Commandes Récentes',
    'dashboard.quick_actions': 'Actions Rapides',
    'dashboard.verify_email': 'Vérifiez votre email',
    'dashboard.verification_sent': 'Email de vérification envoyé',
    'dashboard.check_inbox': 'Vérifiez votre boîte de réception.',
    'dashboard.no_orders': 'Pas encore de commandes',
    'dashboard.start_ordering': 'Commencez à commander pour voir votre activité',
    'orders.title': 'Mes Commandes',
    'orders.subtitle': 'Suivez et gérez vos commandes',
    'orders.pending': 'En Attente',
    'orders.in_progress': 'En Cours',
    'orders.completed': 'Terminée',
    'orders.cancelled': 'Annulée',
    'orders.partial': 'Partielle',
    'orders.refunded': 'Remboursée',
    'orders.no_orders': 'Aucune commande trouvée',
    'orders.order_number': 'Numéro de Commande',
    'orders.service': 'Service',
    'orders.target_url': 'URL Cible',
    'orders.progress': 'Progression',
    'orders.placed_on': 'Passée le',
    'orders.other_orders': 'Autres Commandes',
    'orders.search_placeholder': 'Rechercher par ID ou service...',
    'orders.login_required': 'Connexion Requise',
    'orders.login_to_view': 'Connectez-vous pour voir vos commandes.',
    'services.title': 'Services',
    'services.subtitle': 'Parcourez et commandez des services SMM',
    'services.categories': 'Catégories',
    'services.add_to_cart': 'Ajouter au Panier',
    'services.order_now': 'Commander',
    'services.favorites': 'Favoris',
    'services.select_category': 'Sélectionnez une catégorie',
    'services.select_service': 'Sélectionnez un service',
    'services.enter_url': 'Entrez l\'URL cible',
    'services.enter_quantity': 'Entrez la quantité',
    'services.min_qty': 'Min',
    'services.max_qty': 'Max',
    'services.price_per_k': 'Prix par 1K',
    'services.estimated_time': 'Temps Estimé',
    'services.description': 'Description',
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.checkout': 'Passer la Commande',
    'cart.total': 'Total',
    'cart.clear': 'Vider le Panier',
    'cart.items': 'articles',
    'cart.item': 'article',
    'cart.remove': 'Supprimer',
    'cart.bulk_add': 'Ajout Groupé',
    'cart.quick_repeat': 'Répétition Rapide',
    'cart.processing': 'Traitement...',
    'cart.order_placed': 'Commande Passée!',
    'profile.title': 'Mon Profil',
    'profile.subtitle': 'Gérez vos paramètres',
    'profile.balance': 'Solde',
    'profile.total_spent': 'Total Dépensé',
    'profile.referrals': 'Parrainages',
    'profile.member_since': 'Membre Depuis',
    'profile.change_password': 'Changer le Mot de Passe',
    'profile.update_profile': 'Mettre à Jour',
    'notifications.title': 'Notifications',
    'notifications.mark_all_read': 'Tout marquer comme lu',
    'notifications.empty': 'Aucune notification',
    'notifications.order_update': 'Mise à jour Commande',
    'notifications.low_balance': 'Solde Bas',
    'notifications.new': 'Nouveau',
    'deposit.title': 'Ajouter des Fonds',
    'deposit.subtitle': 'Rechargez votre solde',
    'deposit.amount': 'Montant',
    'deposit.method': 'Méthode de Paiement',
    'deposit.current_balance': 'Solde Actuel',
    'deposit.min_amount': 'Montant minimum',
    'deposit.max_amount': 'Montant maximum',
    'deposit.proceed': 'Procéder au Paiement',
    'support.title': 'Support',
    'support.subtitle': 'Obtenez de l\'aide pour vos commandes',
    'support.new_ticket': 'Nouveau Ticket',
    'support.my_tickets': 'Mes Tickets',
    'support.faq': 'FAQ',
    'support.contact_us': 'Nous Contacter',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'error.something_wrong': 'Quelque chose s\'est mal passé',
    'error.try_again': 'Veuillez réessayer',
    'error.not_found': 'Non trouvé',
    'error.unauthorized': 'Non autorisé',
    'error.loading_failed': 'Échec du chargement',
    'error.dashboard_unavailable': 'Tableau de bord temporairement indisponible',
    'auth.sign_in': 'Se Connecter',
    'auth.sign_up': 'S\'inscrire',
    'auth.sign_out': 'Se Déconnecter',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgot_password': 'Mot de passe oublié?',
    'auth.remember_me': 'Se souvenir de moi',
    'auth.no_account': 'Pas de compte?',
    'auth.have_account': 'Déjà un compte?',
    'auth.please_sign_in': 'Veuillez vous connecter',
    'auth.need_login': 'Connectez-vous pour voir votre tableau de bord',
    'language.title': 'Langue',
    'language.select': 'Sélectionner la Langue',
    'language.changed': 'Langue modifiée',
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.services': 'Dienste',
    'nav.orders': 'Meine Bestellungen',
    'nav.new_order': 'Neue Bestellung',
    'nav.deposit': 'Guthaben aufladen',
    'nav.support': 'Support',
    'nav.profile': 'Profil',
    'nav.favorites': 'Favoriten',
    'nav.track_order': 'Bestellung verfolgen',
    'nav.logout': 'Abmelden',
    'nav.menu': 'Menü',
    'nav.more': 'Mehr',
    'nav.blog': 'Blog',
    'nav.api': 'API',
    'nav.bulk_order': 'Sammelbestellung',
    'nav.smm_services': 'SMM-Dienste',
    'nav.your_balance': 'Ihr Guthaben',
    'common.loading': 'Laden...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.submit': 'Absenden',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.export': 'Exportieren',
    'common.refresh': 'Aktualisieren',
    'common.all': 'Alle',
    'common.view_all': 'Alle anzeigen',
    'common.retry': 'Erneut versuchen',
    'common.close': 'Schließen',
    'common.copy': 'Kopieren',
    'common.copied': 'Kopiert!',
    'common.send': 'Senden',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.confirm': 'Bestätigen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Anzeigen',
    'common.details': 'Details',
    'common.actions': 'Aktionen',
    'common.status': 'Status',
    'common.date': 'Datum',
    'common.price': 'Preis',
    'common.quantity': 'Menge',
    'common.total': 'Gesamt',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'dashboard.welcome': 'Willkommen zurück',
    'dashboard.overview': 'Ihre Kontoübersicht',
    'dashboard.balance': 'Guthaben',
    'dashboard.total_orders': 'Bestellungen gesamt',
    'dashboard.pending': 'Ausstehend',
    'dashboard.completed': 'Abgeschlossen',
    'dashboard.in_progress': 'In Bearbeitung',
    'dashboard.recent_orders': 'Aktuelle Bestellungen',
    'dashboard.quick_actions': 'Schnellaktionen',
    'dashboard.verify_email': 'E-Mail bestätigen',
    'dashboard.verification_sent': 'Bestätigungsmail gesendet',
    'dashboard.check_inbox': 'Prüfen Sie Ihren Posteingang.',
    'dashboard.no_orders': 'Noch keine Bestellungen',
    'dashboard.start_ordering': 'Bestellen Sie, um Ihre Aktivität zu sehen',
    'orders.title': 'Meine Bestellungen',
    'orders.subtitle': 'Verfolgen und verwalten Sie Ihre Bestellungen',
    'orders.pending': 'Ausstehend',
    'orders.in_progress': 'In Bearbeitung',
    'orders.completed': 'Abgeschlossen',
    'orders.cancelled': 'Storniert',
    'orders.partial': 'Teilweise',
    'orders.refunded': 'Erstattet',
    'orders.no_orders': 'Keine Bestellungen gefunden',
    'orders.order_number': 'Bestellnummer',
    'orders.service': 'Dienst',
    'orders.target_url': 'Ziel-URL',
    'orders.progress': 'Fortschritt',
    'orders.placed_on': 'Bestellt am',
    'orders.other_orders': 'Andere Bestellungen',
    'orders.search_placeholder': 'Nach ID oder Dienst suchen...',
    'orders.login_required': 'Anmeldung erforderlich',
    'orders.login_to_view': 'Melden Sie sich an, um Ihre Bestellungen zu sehen.',
    'services.title': 'Dienste',
    'services.subtitle': 'Durchsuchen und bestellen Sie SMM-Dienste',
    'services.categories': 'Kategorien',
    'services.add_to_cart': 'In den Warenkorb',
    'services.order_now': 'Jetzt bestellen',
    'services.favorites': 'Favoriten',
    'services.select_category': 'Kategorie wählen',
    'services.select_service': 'Dienst wählen',
    'services.enter_url': 'Ziel-URL eingeben',
    'services.enter_quantity': 'Menge eingeben',
    'services.min_qty': 'Min',
    'services.max_qty': 'Max',
    'services.price_per_k': 'Preis pro 1K',
    'services.estimated_time': 'Geschätzte Zeit',
    'services.description': 'Beschreibung',
    'cart.title': 'Warenkorb',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.checkout': 'Zur Kasse',
    'cart.total': 'Gesamt',
    'cart.clear': 'Leeren',
    'cart.items': 'Artikel',
    'cart.item': 'Artikel',
    'cart.remove': 'Entfernen',
    'cart.bulk_add': 'Sammel hinzufügen',
    'cart.quick_repeat': 'Schnell wiederholen',
    'cart.processing': 'Verarbeitung...',
    'cart.order_placed': 'Bestellung aufgegeben!',
    'profile.title': 'Mein Profil',
    'profile.subtitle': 'Kontoeinstellungen verwalten',
    'profile.balance': 'Guthaben',
    'profile.total_spent': 'Gesamt ausgegeben',
    'profile.referrals': 'Empfehlungen',
    'profile.member_since': 'Mitglied seit',
    'profile.change_password': 'Passwort ändern',
    'profile.update_profile': 'Profil aktualisieren',
    'notifications.title': 'Benachrichtigungen',
    'notifications.mark_all_read': 'Alle als gelesen markieren',
    'notifications.empty': 'Keine Benachrichtigungen',
    'notifications.order_update': 'Bestellaktualisierung',
    'notifications.low_balance': 'Niedriges Guthaben',
    'notifications.new': 'Neu',
    'deposit.title': 'Guthaben aufladen',
    'deposit.subtitle': 'Laden Sie Ihr Konto auf',
    'deposit.amount': 'Betrag',
    'deposit.method': 'Zahlungsmethode',
    'deposit.current_balance': 'Aktuelles Guthaben',
    'deposit.min_amount': 'Mindestbetrag',
    'deposit.max_amount': 'Höchstbetrag',
    'deposit.proceed': 'Zur Zahlung',
    'support.title': 'Support',
    'support.subtitle': 'Hilfe zu Ihren Bestellungen',
    'support.new_ticket': 'Neues Ticket',
    'support.my_tickets': 'Meine Tickets',
    'support.faq': 'FAQ',
    'support.contact_us': 'Kontakt',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'error.something_wrong': 'Etwas ist schiefgelaufen',
    'error.try_again': 'Bitte versuchen Sie es erneut',
    'error.not_found': 'Nicht gefunden',
    'error.unauthorized': 'Nicht autorisiert',
    'error.loading_failed': 'Laden fehlgeschlagen',
    'error.dashboard_unavailable': 'Dashboard vorübergehend nicht verfügbar',
    'auth.sign_in': 'Anmelden',
    'auth.sign_up': 'Registrieren',
    'auth.sign_out': 'Abmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.forgot_password': 'Passwort vergessen?',
    'auth.remember_me': 'Angemeldet bleiben',
    'auth.no_account': 'Kein Konto?',
    'auth.have_account': 'Bereits registriert?',
    'auth.please_sign_in': 'Bitte melden Sie sich an',
    'auth.need_login': 'Melden Sie sich an, um Ihr Dashboard zu sehen',
    'language.title': 'Sprache',
    'language.select': 'Sprache wählen',
    'language.changed': 'Sprache geändert',
  },
  zh: {
    'nav.dashboard': '控制面板',
    'nav.services': '服务',
    'nav.orders': '我的订单',
    'nav.new_order': '新订单',
    'nav.deposit': '充值',
    'nav.support': '支持',
    'nav.profile': '个人资料',
    'nav.favorites': '收藏',
    'nav.track_order': '跟踪订单',
    'nav.logout': '退出',
    'nav.menu': '菜单',
    'nav.more': '更多',
    'nav.blog': '博客',
    'nav.api': 'API',
    'nav.bulk_order': '批量订购',
    'nav.smm_services': 'SMM服务',
    'nav.your_balance': '您的余额',
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.submit': '提交',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.export': '导出',
    'common.refresh': '刷新',
    'common.all': '全部',
    'common.view_all': '查看全部',
    'common.retry': '重试',
    'common.close': '关闭',
    'common.copy': '复制',
    'common.copied': '已复制！',
    'common.send': '发送',
    'common.back': '返回',
    'common.next': '下一步',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.view': '查看',
    'common.details': '详情',
    'common.actions': '操作',
    'common.status': '状态',
    'common.date': '日期',
    'common.price': '价格',
    'common.quantity': '数量',
    'common.total': '总计',
    'common.yes': '是',
    'common.no': '否',
    'dashboard.welcome': '欢迎回来',
    'dashboard.overview': '账户概览',
    'dashboard.balance': '余额',
    'dashboard.total_orders': '总订单',
    'dashboard.pending': '待处理',
    'dashboard.completed': '已完成',
    'dashboard.in_progress': '进行中',
    'dashboard.recent_orders': '最近订单',
    'dashboard.quick_actions': '快速操作',
    'dashboard.verify_email': '验证邮箱',
    'dashboard.verification_sent': '验证邮件已发送',
    'dashboard.check_inbox': '请检查收件箱。',
    'dashboard.no_orders': '暂无订单',
    'dashboard.start_ordering': '开始下单以查看活动',
    'orders.title': '我的订单',
    'orders.subtitle': '跟踪和管理您的订单',
    'orders.pending': '待处理',
    'orders.in_progress': '进行中',
    'orders.completed': '已完成',
    'orders.cancelled': '已取消',
    'orders.partial': '部分完成',
    'orders.refunded': '已退款',
    'orders.no_orders': '未找到订单',
    'orders.order_number': '订单号',
    'orders.service': '服务',
    'orders.target_url': '目标链接',
    'orders.progress': '进度',
    'orders.placed_on': '下单时间',
    'orders.other_orders': '其他订单',
    'orders.search_placeholder': '按ID或服务搜索...',
    'orders.login_required': '需要登录',
    'orders.login_to_view': '请登录以查看订单。',
    'services.title': '服务',
    'services.subtitle': '浏览和订购SMM服务',
    'services.categories': '分类',
    'services.add_to_cart': '加入购物车',
    'services.order_now': '立即订购',
    'services.favorites': '收藏',
    'services.select_category': '选择分类',
    'services.select_service': '选择服务',
    'services.enter_url': '输入目标链接',
    'services.enter_quantity': '输入数量',
    'services.min_qty': '最小',
    'services.max_qty': '最大',
    'services.price_per_k': '每千价格',
    'services.estimated_time': '预计时间',
    'services.description': '描述',
    'cart.title': '购物车',
    'cart.empty': '购物车为空',
    'cart.checkout': '结算',
    'cart.total': '总计',
    'cart.clear': '清空',
    'cart.items': '件商品',
    'cart.item': '件商品',
    'cart.remove': '移除',
    'cart.bulk_add': '批量添加',
    'cart.quick_repeat': '快速重复',
    'cart.processing': '处理中...',
    'cart.order_placed': '订单已提交！',
    'profile.title': '我的资料',
    'profile.subtitle': '管理账户设置',
    'profile.balance': '余额',
    'profile.total_spent': '总消费',
    'profile.referrals': '推荐',
    'profile.member_since': '注册时间',
    'profile.change_password': '更改密码',
    'profile.update_profile': '更新资料',
    'notifications.title': '通知',
    'notifications.mark_all_read': '全部已读',
    'notifications.empty': '暂无通知',
    'notifications.order_update': '订单更新',
    'notifications.low_balance': '余额不足',
    'notifications.new': '新',
    'deposit.title': '充值',
    'deposit.subtitle': '为账户充值',
    'deposit.amount': '金额',
    'deposit.method': '支付方式',
    'deposit.current_balance': '当前余额',
    'deposit.min_amount': '最低金额',
    'deposit.max_amount': '最高金额',
    'deposit.proceed': '去支付',
    'support.title': '支持',
    'support.subtitle': '获取订单帮助',
    'support.new_ticket': '新工单',
    'support.my_tickets': '我的工单',
    'support.faq': '常见问题',
    'support.contact_us': '联系我们',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'error.something_wrong': '出了点问题',
    'error.try_again': '请重试',
    'error.not_found': '未找到',
    'error.unauthorized': '未授权',
    'error.loading_failed': '加载失败',
    'error.dashboard_unavailable': '控制面板暂时不可用',
    'auth.sign_in': '登录',
    'auth.sign_up': '注册',
    'auth.sign_out': '退出',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.forgot_password': '忘记密码？',
    'auth.remember_me': '记住我',
    'auth.no_account': '没有账户？',
    'auth.have_account': '已有账户？',
    'auth.please_sign_in': '请登录',
    'auth.need_login': '请登录以查看控制面板',
    'language.title': '语言',
    'language.select': '选择语言',
    'language.changed': '语言已更改',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.services': 'सेवाएं',
    'nav.orders': 'मेरे ऑर्डर',
    'nav.new_order': 'नया ऑर्डर',
    'nav.deposit': 'फंड जोड़ें',
    'nav.support': 'सहायता',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.favorites': 'पसंदीदा',
    'nav.track_order': 'ऑर्डर ट्रैक करें',
    'nav.logout': 'लॉग आउट',
    'nav.menu': 'मेन्यू',
    'nav.more': 'और',
    'nav.blog': 'ब्लॉग',
    'nav.api': 'API',
    'nav.bulk_order': 'बल्क ऑर्डर',
    'nav.smm_services': 'SMM सेवाएं',
    'nav.your_balance': 'आपका बैलेंस',
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सेव करें',
    'common.cancel': 'रद्द करें',
    'common.submit': 'सबमिट करें',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.export': 'एक्सपोर्ट',
    'common.refresh': 'रिफ्रेश',
    'common.all': 'सभी',
    'common.view_all': 'सभी देखें',
    'common.retry': 'पुनः प्रयास',
    'common.close': 'बंद करें',
    'common.copy': 'कॉपी',
    'common.copied': 'कॉपी हो गया!',
    'common.send': 'भेजें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.confirm': 'पुष्टि करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.view': 'देखें',
    'common.details': 'विवरण',
    'common.actions': 'क्रियाएं',
    'common.status': 'स्थिति',
    'common.date': 'तारीख',
    'common.price': 'कीमत',
    'common.quantity': 'मात्रा',
    'common.total': 'कुल',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'dashboard.welcome': 'वापसी पर स्वागत है',
    'dashboard.overview': 'आपके खाते का अवलोकन',
    'dashboard.balance': 'बैलेंस',
    'dashboard.total_orders': 'कुल ऑर्डर',
    'dashboard.pending': 'पेंडिंग',
    'dashboard.completed': 'पूर्ण',
    'dashboard.in_progress': 'प्रगति में',
    'dashboard.recent_orders': 'हाल के ऑर्डर',
    'dashboard.quick_actions': 'त्वरित क्रियाएं',
    'dashboard.verify_email': 'ईमेल सत्यापित करें',
    'dashboard.verification_sent': 'सत्यापन ईमेल भेजा गया',
    'dashboard.check_inbox': 'अपना इनबॉक्स जांचें।',
    'dashboard.no_orders': 'अभी तक कोई ऑर्डर नहीं',
    'dashboard.start_ordering': 'अपनी गतिविधि देखने के लिए ऑर्डर करें',
    'orders.title': 'मेरे ऑर्डर',
    'orders.subtitle': 'अपने ऑर्डर ट्रैक और प्रबंधित करें',
    'orders.pending': 'पेंडिंग',
    'orders.in_progress': 'प्रगति में',
    'orders.completed': 'पूर्ण',
    'orders.cancelled': 'रद्द',
    'orders.partial': 'आंशिक',
    'orders.refunded': 'वापस',
    'orders.no_orders': 'कोई ऑर्डर नहीं मिला',
    'orders.order_number': 'ऑर्डर नंबर',
    'orders.service': 'सेवा',
    'orders.target_url': 'लक्ष्य URL',
    'orders.progress': 'प्रगति',
    'orders.placed_on': 'ऑर्डर की तारीख',
    'orders.other_orders': 'अन्य ऑर्डर',
    'orders.search_placeholder': 'ID या सेवा से खोजें...',
    'orders.login_required': 'लॉगिन आवश्यक',
    'orders.login_to_view': 'ऑर्डर देखने के लिए लॉगिन करें।',
    'services.title': 'सेवाएं',
    'services.subtitle': 'SMM सेवाएं ब्राउज़ और ऑर्डर करें',
    'services.categories': 'श्रेणियां',
    'services.add_to_cart': 'कार्ट में जोड़ें',
    'services.order_now': 'अभी ऑर्डर करें',
    'services.favorites': 'पसंदीदा',
    'services.select_category': 'श्रेणी चुनें',
    'services.select_service': 'सेवा चुनें',
    'services.enter_url': 'लक्ष्य URL दर्ज करें',
    'services.enter_quantity': 'मात्रा दर्ज करें',
    'services.min_qty': 'न्यूनतम',
    'services.max_qty': 'अधिकतम',
    'services.price_per_k': '1K की कीमत',
    'services.estimated_time': 'अनुमानित समय',
    'services.description': 'विवरण',
    'cart.title': 'शॉपिंग कार्ट',
    'cart.empty': 'आपका कार्ट खाली है',
    'cart.checkout': 'चेकआउट',
    'cart.total': 'कुल',
    'cart.clear': 'कार्ट खाली करें',
    'cart.items': 'आइटम',
    'cart.item': 'आइटम',
    'cart.remove': 'हटाएं',
    'cart.bulk_add': 'बल्क जोड़ें',
    'cart.quick_repeat': 'त्वरित दोहराव',
    'cart.processing': 'प्रोसेसिंग...',
    'cart.order_placed': 'ऑर्डर हो गया!',
    'profile.title': 'मेरी प्रोफ़ाइल',
    'profile.subtitle': 'खाता सेटिंग्स प्रबंधित करें',
    'profile.balance': 'बैलेंस',
    'profile.total_spent': 'कुल खर्च',
    'profile.referrals': 'रेफरल',
    'profile.member_since': 'सदस्यता की तारीख',
    'profile.change_password': 'पासवर्ड बदलें',
    'profile.update_profile': 'प्रोफ़ाइल अपडेट करें',
    'notifications.title': 'सूचनाएं',
    'notifications.mark_all_read': 'सभी पढ़ा गया',
    'notifications.empty': 'कोई सूचना नहीं',
    'notifications.order_update': 'ऑर्डर अपडेट',
    'notifications.low_balance': 'कम बैलेंस',
    'notifications.new': 'नया',
    'deposit.title': 'फंड जोड़ें',
    'deposit.subtitle': 'अपना बैलेंस रिचार्ज करें',
    'deposit.amount': 'राशि',
    'deposit.method': 'भुगतान विधि',
    'deposit.current_balance': 'वर्तमान बैलेंस',
    'deposit.min_amount': 'न्यूनतम राशि',
    'deposit.max_amount': 'अधिकतम राशि',
    'deposit.proceed': 'भुगतान पर जाएं',
    'support.title': 'सहायता',
    'support.subtitle': 'ऑर्डर में मदद पाएं',
    'support.new_ticket': 'नई टिकट',
    'support.my_tickets': 'मेरी टिकटें',
    'support.faq': 'सामान्य प्रश्न',
    'support.contact_us': 'संपर्क करें',
    'support.whatsapp': 'WhatsApp',
    'support.telegram': 'Telegram',
    'error.something_wrong': 'कुछ गलत हो गया',
    'error.try_again': 'कृपया पुनः प्रयास करें',
    'error.not_found': 'नहीं मिला',
    'error.unauthorized': 'अनधिकृत',
    'error.loading_failed': 'लोड विफल',
    'error.dashboard_unavailable': 'डैशबोर्ड अस्थायी रूप से अनुपलब्ध',
    'auth.sign_in': 'साइन इन',
    'auth.sign_up': 'साइन अप',
    'auth.sign_out': 'साइन आउट',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.forgot_password': 'पासवर्ड भूल गए?',
    'auth.remember_me': 'मुझे याद रखें',
    'auth.no_account': 'खाता नहीं है?',
    'auth.have_account': 'पहले से खाता है?',
    'auth.please_sign_in': 'कृपया साइन इन करें',
    'auth.need_login': 'डैशबोर्ड देखने के लिए लॉगिन करें',
    'language.title': 'भाषा',
    'language.select': 'भाषा चुनें',
    'language.changed': 'भाषा बदली गई',
  },
};

const rtlLanguages: Language[] = ['ar'];

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('preferred_language');
    return (saved as Language) || 'en';
  });

  const isRTL = rtlLanguages.includes(language);

  useEffect(() => {
    localStorage.setItem('preferred_language', language);
    
    // Set document direction for RTL languages
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    // Check merged translations (including platform and section translations)
    const sectionCurrent = sectionTranslations[language] || {};
    const sectionEn = sectionTranslations.en || {};
    const mergedCurrent = { ...translations[language], ...platformTranslations[language], ...sectionCurrent };
    const mergedEn = { ...translations.en, ...platformTranslations.en, ...sectionEn };
    
    let text = mergedCurrent[key] || mergedEn[key] || key;
    
    // Replace parameters like {name} with actual values
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(value));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
