// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tooudgubuhxjbbvzjcgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvb3VkZ3VidWh4amJidnpqY2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDM2MzEsImV4cCI6MjA2NzkxOTYzMX0.gNJfMqhjHxDnCU86kFYeGWrGn4BeYDu_BUv-Jm7wkn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});