import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Slider } from "@/components/ui/slider";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Copy, Download, FileText, Map, RefreshCw, Check, Bot } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface RobotsSitemapEditorProps {
  subdomain: string;
  robotsContent: string;
  onRobotsChange: (content: string) => void;
}

interface SitemapPage {
  path: string;
  name: string;
  priority: number;
  changefreq: string;
  enabled: boolean;
}

export const RobotsSitemapEditor = ({
  subdomain,
  robotsContent,
  onRobotsChange,
}: RobotsSitemapEditorProps) => {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);
  const [robotsRules, setRobotsRules] = useState({
    allowAll: true,
    allowGooglebot: true,
    allowBingbot: true,
    blockBadBots: true,
    blockSensitive: true,
  });

  const [sitemapPages, setSitemapPages] = useState<SitemapPage[]>([
    { path: "/", name: "Homepage", priority: 1.0, changefreq: "daily", enabled: true },
    { path: "/services", name: "Services", priority: 0.9, changefreq: "daily", enabled: true },
    { path: "/new-order", name: "New Order", priority: 0.8, changefreq: "weekly", enabled: true },
    { path: "/blog", name: "Blog", priority: 0.7, changefreq: "weekly", enabled: true },
    { path: "/about", name: "About", priority: 0.5, changefreq: "monthly", enabled: true },
    { path: "/contact", name: "Contact", priority: 0.5, changefreq: "monthly", enabled: true },
    { path: "/terms", name: "Terms", priority: 0.3, changefreq: "yearly", enabled: true },
    { path: "/privacy", name: "Privacy", priority: 0.3, changefreq: "yearly", enabled: true },
  ]);

  const generateRobotsContent = () => {
    let content = "# robots.txt generated by Panel Settings\n";
    content += `# Site: https://${subdomain}.smmpilot.online\n\n`;

    if (robotsRules.allowAll) {
      content += "User-agent: *\n";
      content += "Allow: /\n\n";
    }

    if (robotsRules.allowGooglebot) {
      content += "User-agent: Googlebot\n";
      content += "Allow: /\n\n";
    }

    if (robotsRules.allowBingbot) {
      content += "User-agent: Bingbot\n";
      content += "Allow: /\n\n";
    }

    if (robotsRules.blockBadBots) {
      content += "# Block bad bots\n";
      content += "User-agent: AhrefsBot\nDisallow: /\n\n";
      content += "User-agent: SemrushBot\nDisallow: /\n\n";
    }

    if (robotsRules.blockSensitive) {
      content += "# Block sensitive paths\n";
      content += "Disallow: /api/\n";
      content += "Disallow: /admin/\n";
      content += "Disallow: /panel/\n\n";
    }

    content += `# Sitemap\nSitemap: https://${subdomain}.smmpilot.online/sitemap.xml\n`;
    
    return content;
  };

  const generateSitemapXML = () => {
    const baseUrl = `https://${subdomain}.smmpilot.online`;
    let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
    xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';
    
    sitemapPages.filter(p => p.enabled).forEach(page => {
      xml += '  <url>\n';
      xml += `    <loc>${baseUrl}${page.path}</loc>\n`;
      xml += `    <changefreq>${page.changefreq}</changefreq>\n`;
      xml += `    <priority>${page.priority.toFixed(1)}</priority>\n`;
      xml += '  </url>\n';
    });
    
    xml += '</urlset>';
    return xml;
  };

  const handleCopyRobots = () => {
    navigator.clipboard.writeText(robotsContent || generateRobotsContent());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({ title: "Copied to clipboard" });
  };

  const handleDownloadSitemap = () => {
    const xml = generateSitemapXML();
    const blob = new Blob([xml], { type: 'application/xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'sitemap.xml';
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Sitemap downloaded" });
  };

  const updatePagePriority = (index: number, priority: number) => {
    setSitemapPages(prev => prev.map((p, i) => 
      i === index ? { ...p, priority } : p
    ));
  };

  const togglePageEnabled = (index: number) => {
    setSitemapPages(prev => prev.map((p, i) => 
      i === index ? { ...p, enabled: !p.enabled } : p
    ));
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
      {/* Robots.txt Editor */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-base">
            <Bot className="w-4 h-4" />
            Robots.txt Editor
          </CardTitle>
          <CardDescription className="text-xs">
            Control how search engines crawl your site
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Quick Rules */}
          <div className="space-y-3">
            <Label className="text-sm font-medium">Quick Rules</Label>
            <div className="grid grid-cols-2 gap-3">
              {[
                { key: "allowAll", label: "Allow All Bots" },
                { key: "allowGooglebot", label: "Google Bot" },
                { key: "allowBingbot", label: "Bing Bot" },
                { key: "blockBadBots", label: "Block Bad Bots" },
                { key: "blockSensitive", label: "Block /admin" },
              ].map(rule => (
                <div key={rule.key} className="flex items-center justify-between p-2 bg-accent/30 rounded-lg">
                  <span className="text-xs">{rule.label}</span>
                  <Switch
                    checked={robotsRules[rule.key as keyof typeof robotsRules]}
                    onCheckedChange={(checked) => {
                      setRobotsRules(prev => ({ ...prev, [rule.key]: checked }));
                      onRobotsChange(generateRobotsContent());
                    }}
                    className="scale-75"
                  />
                </div>
              ))}
            </div>
          </div>

          {/* Generated Content */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label className="text-sm">Generated robots.txt</Label>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopyRobots}
                className="h-7 text-xs"
              >
                {copied ? <Check className="w-3 h-3 mr-1" /> : <Copy className="w-3 h-3 mr-1" />}
                Copy
              </Button>
            </div>
            <Textarea
              value={robotsContent || generateRobotsContent()}
              onChange={(e) => onRobotsChange(e.target.value)}
              className="font-mono text-xs h-40 bg-slate-950 text-green-400"
            />
          </div>
        </CardContent>
      </Card>

      {/* Sitemap Generator */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-base">
            <Map className="w-4 h-4" />
            Sitemap.xml Generator
          </CardTitle>
          <CardDescription className="text-xs">
            Auto-generate sitemap for search engines
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Pages List */}
          <div className="space-y-2 max-h-[280px] overflow-y-auto">
            {sitemapPages.map((page, index) => (
              <div
                key={page.path}
                className="flex items-center gap-3 p-2 bg-accent/30 rounded-lg"
              >
                <Switch
                  checked={page.enabled}
                  onCheckedChange={() => togglePageEnabled(index)}
                  className="scale-75"
                />
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium truncate">{page.name}</p>
                  <p className="text-xs text-muted-foreground">{page.path}</p>
                </div>
                <div className="flex items-center gap-2">
                  <Select
                    value={page.changefreq}
                    onValueChange={(v) => {
                      setSitemapPages(prev => prev.map((p, i) => 
                        i === index ? { ...p, changefreq: v } : p
                      ));
                    }}
                  >
                    <SelectTrigger className="h-7 w-20 text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="always">Always</SelectItem>
                      <SelectItem value="hourly">Hourly</SelectItem>
                      <SelectItem value="daily">Daily</SelectItem>
                      <SelectItem value="weekly">Weekly</SelectItem>
                      <SelectItem value="monthly">Monthly</SelectItem>
                      <SelectItem value="yearly">Yearly</SelectItem>
                    </SelectContent>
                  </Select>
                  <Badge variant="outline" className="text-xs w-12 justify-center">
                    {page.priority.toFixed(1)}
                  </Badge>
                </div>
              </div>
            ))}
          </div>

          {/* Actions */}
          <div className="flex gap-2 pt-2 border-t">
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownloadSitemap}
              className="flex-1"
            >
              <Download className="w-4 h-4 mr-2" />
              Download XML
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => {
                navigator.clipboard.writeText(`https://${subdomain}.smmpilot.online/sitemap.xml`);
                toast({ title: "Sitemap URL copied" });
              }}
              className="flex-1"
            >
              <Copy className="w-4 h-4 mr-2" />
              Copy URL
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default RobotsSitemapEditor;
